# Generated by Django 3.0.3 on 2020-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='nome_fantasia',
            field=models.CharField(max_length=100, verbose_name='Nome Fantasia'),
        ),
    ]
