# Generated by Django 3.0.3 on 2020-02-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_auto_20200225_0124'),
        ('escola', '0002_auto_20200221_0311'),
    ]

    operations = [
    ]
