# Generated by Django 3.0.3 on 2020-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_id', models.IntegerField(verbose_name='ID Escola')),
                ('aluno_id', models.IntegerField(verbose_name='ID Aluno')),
                ('instrutor_id', models.IntegerField(verbose_name='ID Instrutor')),
                ('automovel_id', models.IntegerField(verbose_name='ID Automóvel')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
    ]
