# Generated by Django 3.0.3 on 2020-02-25 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='escola_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='data_aula',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='aula',
            name='hora_aula',
            field=models.TimeField(auto_now=True, verbose_name='Hora'),
        ),
    ]
