# Generated by Django 3.0.3 on 2020-02-25 05:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_auto_20200225_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='hora_aula',
            field=models.TimeField(default=datetime.datetime(2020, 2, 25, 5, 16, 38, 182200, tzinfo=utc), verbose_name='Hora de início'),
        ),
    ]
