# Generated by Django 3.0.3 on 2020-02-25 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_auto_20200225_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='hora_aula',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de início'),
        ),
    ]
