# Generated by Django 3.0.3 on 2020-02-25 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0006_auto_20200225_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='hora_aula',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora de início'),
        ),
    ]
