# Generated by Django 3.0.3 on 2020-02-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0007_auto_20200225_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='instrutor_id',
        ),
    ]
