# Generated by Django 3.0.3 on 2020-02-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_auto_20200225_1241'),
        ('aulas', '0008_remove_aula_instrutor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='aluno_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='cpf_aluno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno'),
        ),
    ]
