# Generated by Django 3.0.3 on 2020-02-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0009_auto_20200225_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='cpf_aluno',
            new_name='nome_aluno',
        ),
    ]
