# Generated by Django 3.0.3 on 2020-02-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0009_auto_20200225_0124'),
        ('aulas', '0010_auto_20200225_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='automovel_id',
        ),
        migrations.AddField(
            model_name='aula',
            name='veiculo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='veiculos.Veiculo'),
        ),
    ]
