# Generated by Django 3.0.3 on 2020-02-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_auto_20200211_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(choices=[], default=2020, max_length=4, verbose_name='ano'),
        ),
    ]
