# Generated by Django 3.0.3 on 2020-02-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0007_auto_20200218_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='ano_fabriacao',
            new_name='ano_fabricacao',
        ),
    ]
